spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/spring_boot?serverTimezone=UTC
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
#  过滤返回值的空值
#  jackson:
#    default-property-inclusion: non_null
# server:
#   servlet:
#     context-path: /sell
#打包命令
#  mvn clean package -Dmaven.test.skip=true
#logging:
      ##  pattern:
      ##    console: "%d - %msg%n"
      ###  path: F:/testDocument/cache/
      ##  file: F:/testDocument/cache/sell.log
      ###  新版本level要加root
      ##  level:
    ###    root: debug
    ##    com.imooc.testjava.LoggerTest: debug
wechat:
  mpAppId: wxb406354d0c3fb7b8
  mpAppSercre: c5520090b3a5571b90749befbd1a7cd2
  openAppId: wxc638edbc1aa86b65
  openAppSecret: 61ffefc5d5254190f79591833b981d1a
  mchId: 1497121602
  mchKey: chachadian1QA2WS20180124cde3VFR4
  keyPath: F:/testDocument/cache/sell.log
  notify_url: https://api1.chachadian.cn:8104/wxNotify

projecturl:
  wechatMpAuthorize: http://127.0.0.1
  wechatOpenAuthorize: http://127.0.0.1
  Sell:
  templateId:
    orderStatus: UekbhNdvfwDSLlW1nGqT-6jD7XUruCbPYfijcdhull8

#测试环境打印mybatis的SQL
#logging:
#  level:
#    com:
#      imooc:
#        testjava:
#          dataobject:
#            mapper: trace
mybatis:
  mapper-locations: classpath:mapper/*.xml

aliPay:
  private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCl6nh9KXjkHtA4Zlzof1TcFMd3r2uqyzhLTg8m9aU+6hMufgOifartLl3xatQIYHnqJbaDqOkGfD1G13o+WnW+hC9DGAS4/88xB+jkzm6ckrsxKJnUmpfiKvaZFdMkSrP/MpwQZMi1JhAfFruuPUhPH98J/Pin+UjRCDxRiRRVtYwazeOhakzK/KHI3q0KWWehdkIwn1UfIQif7yCO2SOZgudX/Hrne3HTPOj+IQJu3XH7nevdgfUHYA9X3WYIK6ubDa1ysESM3fSF8eRG7eyYvhNnDIEMCaiR9Ase9t+Qyj1ZigYSxXNk5uvK7dBCfjU01R5danySTMipLx1WxI3pAgMBAAECggEAYS3umNDbwDHUH9TFAmDiYW3CT3XuCEGznVgBQ/6JZUpRJeAlXN1iaj3IRIkf3DA1+FFSj9c1ddj7Qy0eqrrtUEO4MwI0ce9TehJ59Np8qzS+c9KmF4LdB1nGym+gFhezSfxosKl3bbL3ql30W+AFJGM0jnMfabN3VQgP3GoAARq9bQJ+8lmL/51C1sQ+amOvnfi1BDijAlNnaxqyGfco82opVLMTfphTVX4Ch4qb8oAb8j5qPXseAMku++vij7kFVxjhLCJQ7Za/OmANmnxknhknOIFSSDoMZUdcO4yp8uZl4HdkhKJQ9NORE9gTeX5pVDU7p5VT7iIriiM9mmOeIQKBgQDWyuWnB8+bEMvG0RNNdmEzUzovv7V2SJWu8q1ZXm3IaDTgTIDFKgOoSJLOlK6sQzglDNm0Or25RAzOc4wpi9qfT+0yObvtcL0Nq/iLddYjvA3kLHG2etGXbNls2WOqQ4XQLpfVCH4KjhdnW1RdA9H9CiiuKgaPXa0hCIIm4mrdjQKBgQDFvxhLZlegoiI4Zt4h3wyxFjLgHB/9GJQ4zt5SCQzIRL6VZc6J8I3t3N9E4jrQJ3vbE1L1oDJRKHljkFWRZjD51SYpX18y5bX6MpxyUNie8z6grCz/1Ga7sQzKMDpaPPqiZQ1XcM3ZEokbCpu1eMm7OUMHBgwZCdjuYnzd7ZK0zQKBgDFk4WEC49QWDbZ/1/+FTJ7/8a6PWIyF7p4XwpN9qqNei2JVVXuByOuHHPOSr4R/xMaIaPwQUhbrtkI3wjC/r5vZRoO5USUuOtuNA5AWnhMDqPIi4leDcPVwm6Nzbn72Hiycul/MHygQOwOSthjZyw10q5w5n96SPUEOcte8U7T1AoGBAIAUVdgAYaFZYnDFr/qgTcglaK5fiRiVYuuokbbwxaaxX//EARK3DDaUaMhk/1LzP/WVfpY5PF30qSsjwUh7uB0ZQa5qZ26/+i4judERLD1Hr7jBzCOnnyLSekY7FpB8DppAeXO5TJrctpEdPd08bu0lGZTjBdLx3eAJSncz+WHBAoGBANLpmtqv/z5m8sIACk6TP+bnEqUB+6cXGTgDvjwSyLAuh1e0HN0jyuD1qH/wqcaV6biOSEtYtW465s/wFMW6Sjth4ibhTpcT22rOBfQ7DjpIcXssdow9UcX+FoslWXAu+/ZWxtbMr9D67UolNRmJetx/Vb2kNN6CM0oQreNkeR5p
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAlgZ3dbm74Z2mWd1Mk+rda5q2Wwv9UlcUQrpUrGCO4PZVhCTNbJv3KmwhOgdURid7sbAJxNI7HyfmkANSG47qJGGkHkG0et6lYotYEArjDoEYNQYyZX1BThvzFv56YNhecF7IdpDD4nnA9z3D7RMiIoRKKpIJwPA4/7HfUYdKXZ/R5wsqja1ECEO5XAorw7GBy93zmWiwYeyiAnNsZpkYQWmQjSwgoB7gO/1pEGbH55L+tTr4Btq49V/UFGqtrZoL2QVuqwyYV8QHoWwaqW01tRuk177VSWqtvzS4wzdVBzj2rPc1UXlNsDToIcWLn1C6ZET2G2Q3jaBPaiiVm8Z5xwIDAQAB
  app_ID: 2016100900648408
  url: https://openapi.alipaydev.com/gateway.do
  current_url: http://csvtzk.natappfree.cc

